apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitalbow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digitalbow
  template:
    metadata:
      labels:
        app: digitalbow
    spec:
      hostNetwork: true
      containers:
      - name: digitalbow-container
        image: lmxia/digitalbow:v1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kubeedge/
        - mountPath: /dev/ttyS0
          name: modbus-dev0
        - mountPath: /dev/ttyS1
          name: modbus-dev1
      nodeSelector:
        kubernetes.io/hostname: "pi"
      volumes:
      - name: config-volume
        configMap:
          name: device-profile-config-pi
      - name: modbus-dev0
        hostPath:
          path: /dev/ttyS0
      - name: modbus-dev1
        hostPath:
          path: /dev/ttyS1
      restartPolicy: Always
