apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
 name: digitalbow
 namespace: default
spec:
 properties:
  - name: device-status
    description: Device Status Enum Offline,Broken,Syncing,Ready,Locked.
    type:
     string:
      accessMode: ReadWrite
      defaultValue: 'Ready'

