apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: digitalbow-01
  labels:
    description: digitalbow-device-instance
    manufacturer: smilelink
    model: digitalbow
spec:
  deviceModelRef:
    name: digitalbow
  protocol:
    customizedProtocol:
      protocolName: digitalbow
    common:
      com:
        serialPort: '/dev/ttyS0'
        baudRate: 115200
        dataBits: 8
        parity: even
        stopBits: 1
  propertyVisitors:
    - propertyName: device-status
      customizedProtocol:
        protocolName: digitalbow
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - pi
status:
  twins:
    - propertyName: device-status
      reported:
        metadata:
          type: string
        value: ''
      desired:
        metadata:
          type: string
        value: ''
