mqtt:
  server: tcp://127.0.0.1:1883
  username: ""
  password: ""
  certification: ""
configmap: /Users/xialingming/go/src/github.com/kubeedge/mappers-go/mappers/modbus/configmap/configmap_negtest.json
